import {test,expect} from '@playwright/test';
import {createRequire} from 'node:module';
import {readFile} from 'node:fs/promises';
import path from 'node:path';
const frontend=path.resolve(import.meta.dirname,'../../../src/tau_web/frontend');
const require=createRequire(path.join(frontend,'package.json'));
const {build}=require('esbuild');
const css=await readFile(path.resolve(frontend,'../static/piclaw-classic.css'),'utf8');
const bundle=await build({stdin:{contents:`import {h,render} from 'preact';import {ClassicChatFrame} from './src/components/ClassicChatFrame.tsx';import {ClassicComposerSurface} from './src/components/ClassicComposerSurface.tsx';import {ClassicPost} from './src/components/ClassicPost.tsx';import {Timeline} from './src/components/Timeline.tsx';import {Composer} from './src/components/Composer.tsx';import {StatusBar} from './src/components/StatusBar.tsx';import {ClassicSessionControl} from './src/components/ClassicSessionControl.tsx';import {SidePanel} from './src/components/SidePanel.tsx';window.mountClassicNavigation=()=>render(h(SidePanel,{activeTab:'sessions',sessionFilter:'active',onSelectTab:tab=>window.classicPanelSelected=tab,onClose:()=>window.classicPanelClosed=true,onSelectSessionFilter:()=>{}}),document.getElementById('app'));window.mountClassicComposer=()=>render(h(ClassicChatFrame,null,h(Composer,{session:h(ClassicSessionControl,{open:false,onToggle:()=>window.classicSessionsClicked=true}),metadata:h(StatusBar,{dashboardOpen:false,onToggleDashboard:()=>window.classicDashboardClicked=true})})),document.getElementById('app'));window.mountClassicTimeline=()=>{render(h(ClassicChatFrame,null,h(Timeline,null)),document.getElementById('app'));};render(h(ClassicChatFrame,{workspaceOpen:false},h('div',{class:'timeline reverse'},h('div',{class:'timeline-content'},h(ClassicPost,{id:'user',agent:false,author:'You',time:'2m',avatar:'Y'},'Review the workspace.'),h(ClassicPost,{id:'agent',agent:true,author:'Tau',time:'1m',avatar:'τ',actions:h('button',{class:'post-action-btn',type:'button','aria-label':'Copy'},'Copy')},h('p',null,'The API is unchanged.')))),h(ClassicComposerSurface,{session:h('button',{class:'compose-session-switcher-pill',type:'button'},'Sessions'),input:h('textarea',{'aria-label':'Message',rows:1,style:{height:'50px'}}),metadata:h('button',{class:'compose-model-hint compose-model-hint-btn',type:'button'},'test/review-model'),actions:h('button',{class:'send-btn',type:'button'},'Send')})),document.getElementById('app'));`,resolveDir:frontend,loader:'tsx'},bundle:true,write:false,format:'iife',jsx:'automatic',jsxImportSource:'preact',nodePaths:[path.join(frontend,'node_modules')]});
for(const theme of ['light','dark']) test(`classic ${theme} frame uses centered column without visual shell`,async({page})=>{
 await page.route('**/classic-frame-fixture',route=>route.fulfill({contentType:'text/html',body:`<html data-theme="${theme}"><head><meta name="viewport" content="width=device-width, initial-scale=1"></head><body><div id="app"></div></body></html>`}));
 await page.goto('/classic-frame-fixture');
 await page.addStyleTag({content:css});await page.addScriptTag({content:bundle.outputFiles[0].text});
 await expect(page.locator('.app-shell.workspace-collapsed')).toBeVisible();
 await expect(page.locator('.activity-bar,.tab-bar,.app-layout__status-bar')).toHaveCount(0);
 const box=await page.locator('.container').boundingBox();const viewport=page.viewportSize();
 expect(box.width).toBeLessThanOrEqual(viewport.width);
 expect(Math.abs(box.x-(viewport.width-box.width)/2)).toBeLessThanOrEqual(1);
 // WebKit fractional CSS-pixel rounding can differ by 1/64 px.
 expect(Math.abs(box.height-viewport.height)).toBeLessThanOrEqual(0.02);
 await expect(page.locator('.workspace-sidebar')).toHaveAttribute('inert','');
 await expect(page.getByRole('textbox',{name:'Message'})).toBeVisible();
 await expect(page.locator('.compose-top-session-row')).toContainText('Sessions');
 await expect(page.locator('.compose-footer')).toContainText('test/review-model');
 const input=await page.getByRole('textbox',{name:'Message'}).boundingBox();
 const footer=await page.locator('.compose-footer').boundingBox();
 expect(footer.y).toBeGreaterThanOrEqual(input.y+input.height-0.02);
 await expect(page.locator('.compose-box select')).toHaveCount(0);
 const user=await page.locator('#user').boundingBox();
 const agent=await page.locator('#agent').boundingBox();
 expect(user.y+user.height).toBeLessThanOrEqual(agent.y+0.02);
 expect(agent.y+agent.height).toBeLessThanOrEqual((await page.locator('.compose-box').boundingBox()).y+0.02);
 await expect(page.locator('#agent .post-author')).toHaveText('Tau');
 await expect(page.locator('#agent .post-actions button')).toHaveAccessibleName('Copy');
});

test('classic timeline consumes Tau events and preserves collapse focus',async({page})=>{
 await page.route('**/classic-timeline-fixture',r=>r.fulfill({contentType:'text/html',body:'<meta name="viewport" content="width=device-width, initial-scale=1"><div id="app"></div>'}));
 await page.goto('/classic-timeline-fixture');await page.addStyleTag({content:css});await page.addScriptTag({content:bundle.outputFiles[0].text});
 await page.evaluate(()=>window.mountClassicTimeline());
 await page.evaluate(()=>window.dispatchEvent(new CustomEvent('tau:timeline-render',{detail:{selected:true,items:[{id:'one',role:'user',content:'User text',meta:'2m'},{id:'two',role:'assistant',content:'**Agent text**',meta:'1m',attachments:[{mediaId:'report 1',filename:'report.txt',mediaType:'text/plain'},{mediaId:'image-1',filename:'review.png',mediaType:'image/png'}],toolCalls:[{id:'read',name:'read',arguments:{path:'README.md'}}]},{id:'result',role:'tool',toolCallId:'read',content:Array.from({length:25},(_,i)=>`line ${i+1}`).join('\n'),meta:''}]}})));
 await expect(page.locator('.post')).toHaveCount(2);
 await expect(page.locator('#post-two strong')).toHaveText('Agent text');
 await expect(page.locator('#post-two .post-actions .codicon')).toHaveCount(0);
 await expect(page.locator('#post-two .post-actions svg')).toHaveCount(2);
 await page.evaluate(()=>{window.copyAttempts=0;Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.copyAttempts++;if(window.copyAttempts===1)throw Error('denied');window.copiedClassicText=text;}}});});
 await page.locator('#post-two').getByRole('button',{name:'Copy message',exact:true}).click();
 await expect(page.locator('#post-two .post-actions [role="status"]')).toHaveText('Unable to copy message');
 await page.locator('#post-two').getByRole('button',{name:'Copy message',exact:true}).click();
 await expect(page.locator('#post-two .post-actions [role="status"]')).toHaveText('Message copied');
 expect(await page.evaluate(()=>window.copiedClassicText)).toBe('**Agent text**');
 await expect(page.locator('#post-two .post-file-pill')).toHaveAttribute('href','/api/media/report%201/content');
 await expect(page.locator('#post-two .post-file-name')).toHaveText('report.txt');
 await expect(page.locator('#post-two .attachment-chip')).toHaveCount(0);
 await expect(page.locator('#post-two .media-preview img')).toHaveAttribute('src','/api/media/image-1/thumbnail');
 await expect(page.locator('#post-two .media-preview img')).toHaveAttribute('alt','review.png');
 await expect(page.locator('#post-two .media-preview a')).toHaveAttribute('href','/api/media/image-1/content');
 const collapse=page.locator('#post-two').getByRole('button',{name:'Collapse message'});
 await collapse.focus();await page.keyboard.press('Enter');
 const expand=page.locator('#post-two').getByRole('button',{name:'Expand message'});
 await expect(expand).toBeFocused();await expect(expand).toHaveAttribute('aria-expanded','false');
 await expand.click();await expect(page.locator('#post-two strong')).toHaveText('Agent text');
 await page.locator('.agent-thinking-title button').click();
 await expect(page.locator('.agent-thinking-body')).toContainText('line 25');
 await expect(page.locator('.agent-thinking-body pre').last()).toHaveText(Array.from({length:20},(_,i)=>`line ${i+6}`).join('\n'));
 await page.getByRole('button',{name:'Show 5 hidden lines'}).click();
 await expect(page.locator('.agent-thinking-body pre').last()).toHaveText(Array.from({length:25},(_,i)=>`line ${i+1}`).join('\n'));
});

test('classic composer retains adapter anchors and completion events',async({page})=>{
 await page.route('**/classic-compose-fixture',r=>r.fulfill({contentType:'text/html',body:'<meta name="viewport" content="width=device-width, initial-scale=1"><div id="app"></div>'}));
 await page.goto('/classic-compose-fixture');await page.addStyleTag({content:css});await page.addScriptTag({content:bundle.outputFiles[0].text});
 await page.evaluate(()=>window.mountClassicComposer());
 await expect(page.locator('#compose-input')).toBeVisible();
 await expect(page.locator('#compose-delivery-mode')).toBeHidden();
 await expect(page.locator('#compose-submit')).toHaveAccessibleName('Send');
 await expect(page.locator('#compose-attachment-button svg')).toBeVisible();
 await expect(page.locator('#compose-attachment-button .codicon')).toHaveCount(0);
 await page.locator('#compose-input').fill('/help');
 await expect(page.locator('#compose-input')).toHaveValue('/help');
 await page.evaluate(()=>window.dispatchEvent(new CustomEvent('tau:completion-render',{detail:{open:true,index:0,items:[{label:'/help',detail:'Help'}]}})));
 await expect(page.locator('#compose-input')).toHaveAttribute('aria-expanded','true');
 await expect(page.locator('#compose-completion-option-0')).toContainText('/help');
 await expect(page.locator('#compose-form')).toHaveCount(1);
 await page.evaluate(()=>document.getElementById('status-session').textContent='Review session');
 await expect(page.locator('.compose-session-switcher-pill')).toContainText('Review session');
 await page.getByRole('button',{name:'Open sessions'}).click();
 expect(await page.evaluate(()=>window.classicSessionsClicked)).toBe(true);
 await page.evaluate(()=>{window.dispatchEvent(new CustomEvent('tau:status-model',{detail:{model:'test/classic'}}));window.dispatchEvent(new CustomEvent('tau:connection-state',{detail:{state:'live',message:'Live'}}));});
 await expect(page.locator('#status-model')).toHaveText('test/classic');
 await expect(page.locator('#status-stream')).toBeHidden();
 await page.getByRole('button',{name:'Dashboard',exact:true}).click();
 expect(await page.evaluate(()=>window.classicDashboardClicked)).toBe(true);
 await expect(page.locator('.slash-item.active .slash-name')).toHaveText('/help');
 await page.evaluate(()=>window.dispatchEvent(new CustomEvent('tau:attachments-render',{detail:{busy:false,items:[{mediaId:'file-1',filename:'notes.txt',label:'notes.txt'}]}})));
 await expect(page.locator('.compose-file-pill')).toContainText('notes.txt');
 await page.evaluate(()=>window.addEventListener('tau:attachment-remove',e=>window.removedClassicFile=e.detail.mediaId,{once:true}));
 await page.getByRole('button',{name:'Remove attachment notes.txt'}).click();
 await expect.poll(()=>page.evaluate(()=>window.removedClassicFile)).toBe('file-1');
});

test('classic navigation retains panel and close callbacks without activity bar',async({page})=>{
 await page.route('**/classic-nav-fixture',r=>r.fulfill({contentType:'text/html',body:'<meta name="viewport" content="width=device-width, initial-scale=1"><div id="app"></div>'}));
 await page.goto('/classic-nav-fixture');await page.addStyleTag({content:css});await page.addScriptTag({content:bundle.outputFiles[0].text});
 await page.evaluate(()=>window.mountClassicNavigation());
 await expect(page.locator('.activity-bar,.sidebar')).toHaveCount(0);
 for(const name of ['Workspace','Search','Plan','Settings']) {
  await page.getByRole('group',{name:'Navigation',exact:true}).getByRole('button',{name,exact:true}).click();
  expect(await page.evaluate(()=>window.classicPanelSelected)).toBe(name.toLowerCase());
 }
 await page.getByRole('button',{name:'Close sessions drawer'}).click();
 expect(await page.evaluate(()=>window.classicPanelClosed)).toBe(true);
});
