import {test,expect} from '@playwright/test';
import {installSelectedSession} from '../fixtures/selected-session.mjs';
import {installLiveStream} from '../fixtures/live-stream.mjs';
test('classic Settings is modal and keeps form state on close',async({page})=>{
 await installSelectedSession(page);await installLiveStream(page,'tau');await page.goto('/');await expect(page.locator('html')).toHaveAttribute('data-tau-shell-ready','true');
 const cancel=page.getByRole('button',{name:'Cancel',exact:true});await cancel.waitFor({state:'visible',timeout:2000}).catch(()=>{});if(await cancel.isVisible())await cancel.click();
 await page.evaluate(()=>window.savedAuthForm=document.getElementById('auth-form'));
 const trigger=page.getByRole('button',{name:'Open model settings',exact:true});await trigger.click();
 const dialog=page.getByRole('dialog',{name:'Settings',exact:true});
 await expect(dialog).toBeVisible();
 await page.evaluate(async()=>{await Promise.all(document.getAnimations().filter(a=>Number.isFinite(a.effect?.getComputedTiming().endTime)).map(a=>a.finished.catch(()=>{})));});
 const box=await dialog.boundingBox();
 expect(box.x).toBeGreaterThanOrEqual(0);expect(box.y).toBeGreaterThanOrEqual(0);
 expect(box.x+box.width).toBeLessThanOrEqual(page.viewportSize().width+1);
 expect(box.y+box.height).toBeLessThanOrEqual(page.viewportSize().height+1);
 await expect(page.locator('#model-input')).toBeFocused();
 expect(await page.locator('#compose-input').evaluate(el=>!!el.closest('[inert]'))).toBe(true);
 await page.locator('#model-input').fill('unsaved-model');await page.keyboard.press('Escape');
 await expect(page.getByRole('dialog',{name:'Settings',exact:true})).toBeHidden();await expect(trigger).toBeFocused();
 await trigger.click();await expect(page.locator('#model-input')).toHaveValue('unsaved-model');
 expect(await page.evaluate(()=>window.savedAuthForm===document.getElementById('auth-form'))).toBe(true);
 const close=page.getByRole('button',{name:'Close settings',exact:true});
 await close.focus();await page.keyboard.press('Shift+Tab');
 expect(await page.evaluate(()=>document.activeElement?.closest('[role="dialog"]')?.getAttribute('aria-labelledby'))).toBe('classic-settings-title');
 await page.keyboard.press('Tab');await expect(close).toBeFocused();
 await close.click();
 expect(await page.locator('#compose-input').evaluate(el=>!!el.closest('[inert]'))).toBe(false);
 await expect(trigger).toBeFocused();
});
