import {test,expect} from '@playwright/test';
import {installLiveStream} from '../fixtures/live-stream.mjs';
import {fixedTime,userText,agentText} from '../fixtures/visual-state.mjs';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
const root='/opt/piclaw/releases/piclaw-2.15.3-linux-x64-baseline/app/runtime/web';
for(const colorScheme of ['light','dark']) test('genuine classic '+colorScheme+' populated reference',async({page},info)=>{
await page.emulateMedia({colorScheme});await page.clock.setFixedTime(new Date(fixedTime));await installLiveStream(page,'piclaw');
let unknown=new Set(),errors=[];
page.on('pageerror',e=>errors.push(e.message));
await page.route('http://classic.test/**',async r=>{const p=new URL(r.request().url()).pathname;const json=x=>r.fulfill({json:x});
if(p==='/editor-vendor/codemirror.js')return r.fulfill({body:await readFile(root+'/../extensions/viewers/editor/vendor/codemirror.js'),contentType:'application/javascript'});
if(p==='/'||p.startsWith('/static/')){try{return await r.fulfill({body:await readFile(root+(p==='/'?'/static/classic/index.html':p)),contentType:p==='/'?'text/html':p.endsWith('.js')?'application/javascript':p.endsWith('.css')?'text/css':undefined});}catch{}}
if(p==='/timeline')return json({posts:[{id:2,data:{type:'agent_response',content:agentText},timestamp:'2026-09-01T12:01:00Z'},{id:1,data:{type:'user_message',content:userText},timestamp:'2026-09-01T12:00:00Z'}],has_more:false});
if(p==='/manifest.json')return json({name:'Piclaw classic reference',short_name:'Piclaw',start_url:'/',display:'standalone',icons:[]});
if(p==='/workspace/index-status')return json({status:'idle'});
if(p==='/workspace/visibility'||p==='/agent/push/presence')return json({ok:true});
if(p==='/agent/settings/quick-actions')return json({settings:{}});
if(p==='/agent/commands')return json({commands:[]});
if(p==='/agent/queue-state')return json({items:[]});
if(p==='/agent/autoresearch/status')return json({status:'idle'});
if(p==='/agent/models')return json({current:'test/review-model',models:['test/review-model'],oobe:{provider_ready_completed_instance:true}});
if(p==='/agent/status')return json({status:'idle',data:null});
if(p==='/agent/context')return json({tokens:null});
if(p==='/agent/roster')return json({agents:[]});
if(p==='/agent/branches'||p==='/agent/active-chats')return json({chats:[]});
if(p==='/workspace/tree')return json({root:{name:'workspace',path:'',type:'directory',children:[]}});
if(p==='/agent/addons/web-entries')return json({entries:[]});
if(p.includes('events')||p==='/sse/stream')return r.fulfill({contentType:'text/event-stream',body:': fixture\n\n'});
unknown.add(p);return r.fulfill({status:404,body:''});});
await page.goto('http://classic.test/',{waitUntil:'domcontentloaded'});
await page.getByText('The API is unchanged.').waitFor();
await page.evaluate(() => document.fonts.ready);
if (errors.length || unknown.size) throw new Error(JSON.stringify({errors,unknown:[...unknown]}));
const structure = await page.locator('.app-shell, .container, .timeline, .post, .compose-box, .compose-container, .compose-footer, textarea').evaluateAll(els => els.map(el => ({tag:el.tagName,className:el.className,rect:el.getBoundingClientRect().toJSON(),html:el.outerHTML.slice(0,1800)})));
await expect(page.locator('.compose-model-hint').first()).toContainText('test/review-model');
const dir='/workspace/tmp/piclaw-classic-reference';await mkdir(dir,{recursive:true});
await page.screenshot({path:dir+'/'+info.project.name+'-'+colorScheme+'.png'});
await writeFile(dir+'/'+info.project.name+'-'+colorScheme+'.json',JSON.stringify({unknown:[...unknown],errors,structure},null,2));
expect(errors).toEqual([]);expect([...unknown]).toEqual([]);
});
